name: build

on: [push]

jobs:
  build:
    name: Builds, verifies, and publishes
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - uses: actions/cache@master
        env:
          cache-name: cache-maven-dependencies
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{hashFiles('**/gradle.properties') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Set up JDK 11
        uses: actions/setup-java@master
        with:
          version: 11

      - name: Build and verify
        run: ./gradlew build
