name: build

on:
  push:
    paths-ignore:
      - README.md
  pull_request:
    paths-ignore:
      - README.md

jobs:
  build:
    name: Builds and verifies
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Restore cached Gradle local
        id: gradle-cache
        uses: actions/cache@master
        env:
          cache-name: cache-gradle
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ env.cache-name }}
          restore-keys: |
            ${{ runner.os }}-gradle-${{ env.cache-name }}
            ${{ runner.os }}-gradle-
            ${{ runner.os }}-

      - name: Set up JDK 11
        uses: actions/setup-java@master
        with:
          version: 11

      - name: Build and verify
        run: ./gradlew --no-daemon clean build
